-- Baseline kortu importas (400). Paleisti PO TRUNCATE. card_number=<frakcija>/<failas> (unikalus); image_url URL-encoded.
-- Tipas is failo vardo; faction-named -> Padaras. is_champion=true cempionams. cost/atk/hp/rarity=NULL (veliau).
INSERT INTO public.cards (card_number, name, faction_id, card_type_id, effect_text, image_url, status, is_champion) VALUES
('demonu-orda/CURSE-1','Didysis suvaržymas',9,8,'Prakeikėjas pasirenka aukos kuriam padaro .','/cards/demonu-orda/CURSE-1.webp','active',false),
('demonu-orda/CURSE-10','Pikti liežuviai',9,8,'Aukos patiria -1 tada -1 patiria aukos','/cards/demonu-orda/CURSE-10.webp','active',false),
('demonu-orda/CURSE-11','Juodieji pirštai',9,8,'Auka renkasi parodyti ranką, arba aukos patiria po -1 už kiekvieną rankoje turimą kortą.','/cards/demonu-orda/CURSE-11.webp','active',false),
('demonu-orda/CURSE-12','Gazzaros žymė',9,8,', jei Panaikina visų aukos tokių nėra, prakeikėjas pasirenka 1 , kuris patiria -1','/cards/demonu-orda/CURSE-12.webp','active',false),
('demonu-orda/CURSE-13','Apsėstas įsakymas',9,8,'Pirmos šio ėjimo atakos taikinį renkasi prakeikėjas.','/cards/demonu-orda/CURSE-13.webp','active',false),
('demonu-orda/CURSE-14','Pelenų liežuvis',9,8,'Kitas aukos +100 korta kainuoja .','/cards/demonu-orda/CURSE-14.webp','active',false),
('demonu-orda/CURSE-2','Siela ant kabliuko',9,8,'Prakeikėjas iš kaladės, rankos arba kapinyno iškviečia „Impas“.','/cards/demonu-orda/CURSE-2.webp','active',false),
('demonu-orda/CURSE-3','Klykianti siela',9,8,'Aukos patiria -1 . Jei auka turi 3 arba daugiau kortų rankoje, prakeikėjas iš kaladės, rankos arba kapinyno iškviečia 1 „Impas“.','/cards/demonu-orda/CURSE-3.webp','active',false),
('demonu-orda/CURSE-4','Kraujo skola',9,8,'Aukos','/cards/demonu-orda/CURSE-4.webp','active',false),
('demonu-orda/CURSE-5','Kraujo duoklė',9,8,'Jeigu auka šį ėjimą išleidžia visą savo . Aukos','/cards/demonu-orda/CURSE-5.webp','active',false),
('demonu-orda/CURSE-6','Ritualinis paaukojimas',9,8,'Auka renkasi savo -2 -3 . Jei , kuris patiria nėra, aukos patiria .','/cards/demonu-orda/CURSE-6.webp','active',false),
('demonu-orda/CURSE-7','Besiklausanti žaizda',9,8,'Aukos patiria -1 su mažiausiai . Jei jų keli, taikinį renkasi auka.','/cards/demonu-orda/CURSE-7.webp','active',false),
('demonu-orda/CURSE-8','Belzatoro akis',9,8,'Auka parodo savo rankos kortas.','/cards/demonu-orda/CURSE-8.webp','active',false),
('demonu-orda/CURSE-9','Pragaro sutartis',9,8,'Kita aukos korta kainuoja +100 .','/cards/demonu-orda/CURSE-9.webp','active',false),
('demonu-orda/CURSE','Šnabždėjimas po oda',9,8,'Aukos turintis daugiausiai patiria -1 , jei jų keli, po -1 patiria visi.','/cards/demonu-orda/CURSE.webp','active',false),
('demonu-orda/Demonu_Orda_1','Oglor’as Klaidintojas',9,12,'- Kai aktyvuojamas grąžinkite šį , iš kapinyno į kovos lauką.','/cards/demonu-orda/Demonu_Orda_1.webp','active',false),
('demonu-orda/Demonu_Orda_10','Tamsos Altorius',9,12,'- Burtai vietoje gydymo daro žalą.','/cards/demonu-orda/Demonu_Orda_10.webp','active',false),
('demonu-orda/Demonu_Orda_11','Kankintojo Kirvis',9,12,'- Kas ėjimą gali padaryti sau -2 , priverčiant auką traukti kortas tol, kol ištrauks . Kitas kortas įmaišo atgal į kaladę.','/cards/demonu-orda/Demonu_Orda_11.webp','active',false),
('demonu-orda/Demonu_Orda_12','Vethagog’o Kalnas',9,12,'Visi priešininko -4 -4 patiria po už kiekvieną kovos lauke esantį','/cards/demonu-orda/Demonu_Orda_12.webp','active',false),
('demonu-orda/Demonu_Orda_13','Trinak’as',9,12,'Gazzar’a Kerštingasis - Kas Pašalinkite kartą, kai vieną sunaikina -2 žalos modifikatorių iš savo kaladės iki . priešininko suteikia sau +2 žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_13.webp','active',false),
('demonu-orda/Demonu_Orda_14','Trinak’as',9,12,'Digolan’as Kerštingasis - įmaišykite Pašalinkite2vi -2 . žalos kortas iš rankos Traukite kortą. į priešininko iš savo kaladės iki žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_14.webp','active',false),
('demonu-orda/Demonu_Orda_15','Trinak’as',9,12,'Mubaal’as Kerštingasis - Priešininkas Pašalinkite vieną traukia žalos -2 kortas kortas iš rankos į priešininko iš savo kaladės iki tol, kol ištrauks kortą. Likusias žaidimo pabaigos. kortas įmaišo atgal į kaladę.','/cards/demonu-orda/Demonu_Orda_15.webp','active',false),
('demonu-orda/Demonu_Orda_16','Trinak’as',9,12,'Jarot’as Kerštingasis - Visa Pašalinkite žala kurią vieną patiria žalos -2 visi kortas iš rankos į priešininko iš savo kaladės iki priešininko pridedama prie žaidimo pabaigos. jūsų gyvybės taškų.','/cards/demonu-orda/Demonu_Orda_16.webp','active',false),
('demonu-orda/Demonu_Orda_17','Trinak’as',9,12,'Astrareg’as Kerštingasis - Iš Pašalinkite kaladės, rankos vieną -2 arba žalos kortas iš rankos į priešininko kapinyno iškviečia 2 „Impas“. iš savo kaladės iki žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_17.webp','active',false),
('demonu-orda/Demonu_Orda_18','Trinak’as',9,12,'Dolgid’as Kerštingasis - Sunaikina Pašalinkitemažiausiai vieną -2 puolimo žalos kortasturintį iš rankos į priešininkoiriš savo kaladės iki taškų priešininko žaidimo pabaigos. įgyja jo puolimo taškus.','/cards/demonu-orda/Demonu_Orda_18.webp','active',false),
('demonu-orda/Demonu_Orda_19','Trinak’as',9,12,'Ongromig’as Kerštingasis - priešininko Pašalinkite vienąpraranda po -2 žalos kortas iš rankos į priešininko iš savo kaladės iki -2 kas kartą traukdamas kortą. žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_19.webp','active',false),
('demonu-orda/Demonu_Orda_2','Didysis Belzatoras',9,12,'- Ėjimo pradžioje sunaikina priešininko su daugiausiai gyvybės taškų, jei jų nėra įmaišykite .','/cards/demonu-orda/Demonu_Orda_2.webp','active',false),
('demonu-orda/Demonu_Orda_20','Trinak’as',9,12,'Viglal’as Kerštingasis - Kai Pašalinkite sunaikinamas vieną -2 bet kuris žalos kortas iš rankos į priešininko savo kaladės iki suteikia savo +1 taipiš pat žaidimo pabaigos. įmaišykite .','/cards/demonu-orda/Demonu_Orda_20.webp','active',false),
('demonu-orda/Demonu_Orda_21','Trinak’as',9,12,'Riglek’as Kerštingasis - Pašalinkite kai puola priešininko vieną -2 žalos kortas iš rankos į priešininko iš savo kaladės iki suteikia savo +1 . žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_21.webp','active',false),
('demonu-orda/Demonu_Orda_22','Kančių knyga',9,12,'- -3','/cards/demonu-orda/Demonu_Orda_22.webp','active',false),
('demonu-orda/Demonu_Orda_23','Pragaro Liepsna',9,12,'Visi ir kovos lauke lieka su 1 . Įmaišykite 2','/cards/demonu-orda/Demonu_Orda_23.webp','active',false),
('demonu-orda/Demonu_Orda_24','Kraujas už kraują',9,12,'Priešininko patiria -4 . Išmeta 2 savo pasirinktas kortas iš rankos į kapinyną.','/cards/demonu-orda/Demonu_Orda_24.webp','active',false),
('demonu-orda/Demonu_Orda_25','Trinak’as',9,12,'Geralel’as Kerštingasis - įmaišykite Pašalinkite1vieną. -2 žalos kortas iš rankos į priešininko iš savo kaladės iki žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_25.webp','active',false),
('demonu-orda/Demonu_Orda_26','Dyglių velnias',9,12,NULL,'/cards/demonu-orda/Demonu_Orda_26.webp','active',false),
('demonu-orda/Demonu_Orda_27','Prakeiktasis žvėris',9,12,NULL,'/cards/demonu-orda/Demonu_Orda_27.webp','active',false),
('demonu-orda/Demonu_Orda_28','Trinak’as',9,12,'Gargarmaras Kerštingasis - atakuodamas Pašalinkite vieną padaro . -2 žalos kortas iš rankos į priešininko iš savo kaladės iki žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_28.webp','active',false),
('demonu-orda/Demonu_Orda_29','Gilus pavydas',9,12,'Įmaišykite po priešininko','/cards/demonu-orda/Demonu_Orda_29.webp','active',false),
('demonu-orda/Demonu_Orda_3','Regnaras Mėgdžiotojas',9,12,'- Pasirink priešininko kapinyne esančio efektą ir nukopijuok jį. - Kas kartą, kai sunaikinamas bet kuris įmaišykite .','/cards/demonu-orda/Demonu_Orda_3.webp','active',false),
('demonu-orda/Demonu_Orda_30','Trinak’as',9,12,'Kraujasiurbys Kerštingasis kirmis - Pasirinktas Pašalinkite vieną priešininko -2 žalos kortas iš rankos į priešininko patiria -1 , o jūsų +1 iš. savo kaladės iki žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_30.webp','active',false),
('demonu-orda/Demonu_Orda_31','Gniuždantis žvilgsnis',9,12,'Visi priešininko esantys kovos lauke patiria -2 . Įmaišykite','/cards/demonu-orda/Demonu_Orda_31.webp','active',false),
('demonu-orda/Demonu_Orda_32','Demoniška akistata',9,12,'Sunaikina po brangiausią abiejose kovos lauko pusėse. Jų prideda','/cards/demonu-orda/Demonu_Orda_32.webp','active',false),
('demonu-orda/Demonu_Orda_33','Trinak’as',9,12,'Velnio advokatas Kerštingasis - Sugeria Pašalinkite savo vieną patiriamą -2 žalos kortas iš rankos į priešininko iš savo kaladės iki žalą ir perkelia ją sau. žaidimo pabaigos.','/cards/demonu-orda/Demonu_Orda_33.webp','active',false),
('demonu-orda/Demonu_Orda_34','Gyvasties išsiurbimas',9,12,'Padaro -3 pasirinktam . Jei sunaikinamas, prideda +3 pasirinktam kovos lauke esančiam tipo','/cards/demonu-orda/Demonu_Orda_34.webp','active',false),
('demonu-orda/Demonu_Orda_35','Demono apgavystė',9,12,'Paveikia pasirinktą priešininko kovos lauke ir jį valdo iki savo ėjimo pabaigos.','/cards/demonu-orda/Demonu_Orda_35.webp','active',false),
('demonu-orda/Demonu_Orda_4','Okuliaras',9,12,'- Peržiūri 6 viršutines priešininko kaladės kortas ir pasirinktas 3 išmeta į kapinyną.','/cards/demonu-orda/Demonu_Orda_4.webp','active',false),
('demonu-orda/Demonu_Orda_5','Zorzok’as Alkanasis',9,12,'- Padaro po -1 visiems kovos lauke. Visa padaryta žala pridedama prie šio puolimo taškų.','/cards/demonu-orda/Demonu_Orda_5.webp','active',false),
('demonu-orda/Demonu_Orda_6','Kryžkėlės Demonas',9,12,'Sugrąžina 1 pasirinktą tipo iš kapinyno į kovos lauką su +2 -2','/cards/demonu-orda/Demonu_Orda_6.webp','active',false),
('demonu-orda/Demonu_Orda_7','Rajūnas Pak-erael’is',9,12,'- Kartą per ėjimą, gali sunaikinti pasirinktą iš priešininko kaladės, kad suteiktų sau +3 +3 .','/cards/demonu-orda/Demonu_Orda_7.webp','active',false),
('demonu-orda/Demonu_Orda_8','Klastingoji Aelot’ė',9,12,'- Įmaišykite 2','/cards/demonu-orda/Demonu_Orda_8.webp','active',false),
('demonu-orda/Demonu_Orda_9','Trinak’as',9,12,'Trinak’as Kerštingasis - Pašalinkite vieną -2 žalos modifikatorių iš savo kaladės modifikatorių iš savo kaladės iki iki žaidimo žaidimo pabaigos. pabaigos.','/cards/demonu-orda/Demonu_Orda_9.webp','active',false),
('vryhioko-gauja/FIELD + Rarity-1','Mirties Pelkė',8,10,'Veikėjai su paskutinis noras miršta iš karto po iškvietimo.','/cards/vryhioko-gauja/FIELD%20%2B%20Rarity-1.webp','active',false),
('vryhioko-gauja/FIELD + Rarity','Aidų tarpeklis',8,10,'- efektas aktyvuojasi 2 kartus.','/cards/vryhioko-gauja/FIELD%20%2B%20Rarity.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_175','Apsukrusis Slelk’as',8,12,'- įgyja po +3 nuo kiekvieno draugiško esančio kovos lauke.','/cards/vryhioko-gauja/Vryhioko_gauja_175.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_176','Egzekutorius Prol’as',8,12,'- sunaikina visus sužeistus ir kovos lauke.','/cards/vryhioko-gauja/Vryhioko_gauja_176.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_177','Nepailstantysis Zird’as',8,12,'- Grįžta į ranką arba keliauja į kapinyną.','/cards/vryhioko-gauja/Vryhioko_gauja_177.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_178','Matriarchė Gorta',8,12,'- padaro pasirinktam - kai puola padaro -','/cards/vryhioko-gauja/Vryhioko_gauja_178.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_179','Gurd’as',8,12,'- bet kuriam tipo atakuojant “Gurd’as” įgyja +1','/cards/vryhioko-gauja/Vryhioko_gauja_179.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_180','Vrold’as',8,12,'- Puldamas padaro žalą ir šalia taikinio esantiems','/cards/vryhioko-gauja/Vryhioko_gauja_180.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_181','Zabelx’as',8,12,'- žala padaroma visiems dvigubėja.','/cards/vryhioko-gauja/Vryhioko_gauja_181.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_182','Apgaulingos taktikos',8,12,'Visi draugiški kurie šį ėjimą puolė, gali pulti dar kartą. Už kiekvieną paveiktą traukite po kortą.','/cards/vryhioko-gauja/Vryhioko_gauja_182.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_183','Rizikūnas Zoics’as',8,12,'- kai šis atakuoja Dviguba žala. Pusė žalos sau.','/cards/vryhioko-gauja/Vryhioko_gauja_183.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_184','Lignag''as garsusis',8,12,'- visi tipo įgyja +1 kiekvienam atskiras priešininko savo','/cards/vryhioko-gauja/Vryhioko_gauja_184.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_185','Sprogiosios statinės',8,12,'- ėjimo pradžioje daro po -1 visiems ir Kai “Sprogiosios statinės” sunaikinamos visi patiria -4 .','/cards/vryhioko-gauja/Vryhioko_gauja_185.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_186','Maitėdų būrys',8,12,'Padaro -2 ir','/cards/vryhioko-gauja/Vryhioko_gauja_186.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_187','Retaliacija',8,12,'Padaro -3 po -1 pasirinktam visiems kitiems','/cards/vryhioko-gauja/Vryhioko_gauja_187.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_188','Vramaarx’as',8,12,'- kai “Vramaarx’as” padaro žalos priešininko','/cards/vryhioko-gauja/Vryhioko_gauja_188.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_189','Dručkis Onvac’as',8,12,'- turi +4 per priešininko ėjimą.','/cards/vryhioko-gauja/Vryhioko_gauja_189.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_190','Kovos eskalacija',8,12,'Traukite kortą už kiekvieną sužeistą draugišką','/cards/vryhioko-gauja/Vryhioko_gauja_190.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_191','Skrajūnas Gaggar''as',8,12,'- padaro -2 draugiškiems','/cards/vryhioko-gauja/Vryhioko_gauja_191.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_192','Tretvoc’as',8,12,'- atgimsta kovos lauke su 1 Efektas galioja 1 kartą per žaidimą.','/cards/vryhioko-gauja/Vryhioko_gauja_192.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_193','Vadas Vryhiok’as',8,12,'- Tol, kol yra sužeistas, įgyja +3 .','/cards/vryhioko-gauja/Vryhioko_gauja_193.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_194','Liepsnojantis Kakburk''as',8,12,'- padaro -1 pasirinktam','/cards/vryhioko-gauja/Vryhioko_gauja_194.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_195','Cheminis Zibnad''as',8,12,'- šis patiria .','/cards/vryhioko-gauja/Vryhioko_gauja_195.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_196','Guknuk''as Baliauninkas',8,12,'- trauk kortą. Jei tai Iškviesk į kovos lauką. Išmesk į kapinyną.','/cards/vryhioko-gauja/Vryhioko_gauja_196.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_197','Sprogmenų dėžutė',8,12,'- Kai draugiški atakuoja , padaro dvigubą žalą, tačiau po puolimo sunaikinami.','/cards/vryhioko-gauja/Vryhioko_gauja_197.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_198','Jakz’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_198.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_199','Orm’as',8,12,'- Tol kol yra sužeistas, įgija +1 .','/cards/vryhioko-gauja/Vryhioko_gauja_199.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_200','Gilez’as',8,12,'- Gali atakuoti turinčius 2 kartus.','/cards/vryhioko-gauja/Vryhioko_gauja_200.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_201','Jakz’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_201.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_202','Gilez’as',8,12,'ir','/cards/vryhioko-gauja/Vryhioko_gauja_202.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_203','Gnegs’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_203.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_204','Goblinas maitėda',8,12,'- Traukti 2 kortas.','/cards/vryhioko-gauja/Vryhioko_gauja_204.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_205','Glort’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_205.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_206','Kruigex’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_206.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_207','Goblinų įniršis',8,12,'Suteikia visiems tipo esantiems kovos lauke +2 +2 .','/cards/vryhioko-gauja/Vryhioko_gauja_207.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_208','Magmos granata',8,12,'Visi ir','/cards/vryhioko-gauja/Vryhioko_gauja_208.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_209','Ledo spindulys',8,12,'Padaro','/cards/vryhioko-gauja/Vryhioko_gauja_209.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_210','Wrosxa',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_210.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_211','Srefėja',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_211.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_212','Goblinas žvalgas',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_212.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_213','Goblinas tykotojas',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_213.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_214','Frybs’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_214.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_215','Antras kvėpavimas',8,12,'Suteikia pasirinktam, sužeistam +2','/cards/vryhioko-gauja/Vryhioko_gauja_215.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_216','Pelkių palyda',8,12,'Suteikia pasirinktam -1 +2 .','/cards/vryhioko-gauja/Vryhioko_gauja_216.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_217','Edaald’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_217.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_218','Ienka',8,12,'- Padaro -1 arba','/cards/vryhioko-gauja/Vryhioko_gauja_218.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_219','Grurk’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_219.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_220','Shiarxi',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_220.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_221','Zrusb’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_221.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_222','Hokieg’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_222.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_223','Chaoso pakylėtas',8,12,'Suteikia pasirinktam +5 . Savo ėjimo pabaigoje tas sunaikinamas.','/cards/vryhioko-gauja/Vryhioko_gauja_223.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_224','Dagberd’as',8,12,'- Atakuodamas padaro','/cards/vryhioko-gauja/Vryhioko_gauja_224.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_225','Pasala',8,12,'Traukite kortas tol, kol rankoje turėsite 4 kortas.','/cards/vryhioko-gauja/Vryhioko_gauja_225.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_226','Gnaard’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_226.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_227','Wynsa',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_227.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_228','Kalx’as',8,12,'- Atakuodamas padaro','/cards/vryhioko-gauja/Vryhioko_gauja_228.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_229','Ubbes’as',8,12,NULL,'/cards/vryhioko-gauja/Vryhioko_gauja_229.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_230','Inžinierius Skrag’as',8,12,'12 - padaro -4 priešininko tavo pasirinktam tavo . Suteikia pasirinktam tavo +3 -2 - padaro po visiems','/cards/vryhioko-gauja/Vryhioko_gauja_230.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_231','Inžinierius Skrag’as',8,12,'15 - padaro -6 priešininko tavo pasirinktam tavo . Suteikia pasirinktam tavo +5 -3 - padaro po visiems','/cards/vryhioko-gauja/Vryhioko_gauja_231.webp','active',false),
('vryhioko-gauja/Vryhioko_gauja_232','Inžinierius Skrag’as',8,12,'19 - padaro -8 priešininko tavo pasirinktam tavo . Suteikia pasirinktam tavo +7 -4 - padaro po visiems','/cards/vryhioko-gauja/Vryhioko_gauja_232.webp','active',false),
('inkvizicijos-legionas/ARTIFACT-1','Inkvizicijos knyga',10,11,'- kai sunaikinamas draugiškas suteikia visiems po +1','/cards/inkvizicijos-legionas/ARTIFACT-1.webp','active',false),
('inkvizicijos-legionas/ARTIFACT','Inkvizicijos bokštas',10,11,'- visi draugiški kiekvieno ėjimo pradžioje įgauna po +1 +1 .','/cards/inkvizicijos-legionas/ARTIFACT.webp','active',false),
('inkvizicijos-legionas/CHAMPIOIN_Phase_1','Nefilimas Galdrianas',10,9,'Suteikia pasirinktam 12 . Suteikia +3 savo Pasirinktam suteikia +2 . +2 iki sekančio ėjimo.','/cards/inkvizicijos-legionas/CHAMPIOIN_Phase_1.webp','active',true),
('inkvizicijos-legionas/CHAMPIOIN_Phase_2','Nefilimas Galdrianas',10,9,'Suteikia ir +2 pasirinktam Suteikia +6 savo Pasirinktam suteikia +4 15 . . +4 iki sekančio ėjimo.','/cards/inkvizicijos-legionas/CHAMPIOIN_Phase_2.webp','active',true),
('inkvizicijos-legionas/CHAMPIOIN_Phase_3','Nefilimas Galdrianas',10,9,'Suteikia ir +4 pasirinktam Suteikia +9 savo Pasirinktam suteikia +6 19 . . +6 iki sekančio ėjimo.','/cards/inkvizicijos-legionas/CHAMPIOIN_Phase_3.webp','active',true),
('inkvizicijos-legionas/CHARACTER_1-1','Elys Matviga',10,12,'- atstato pilnus gyvybės taškus visiems draugiškiems kovos lauke.','/cards/inkvizicijos-legionas/CHARACTER_1-1.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-10','Dulvydas Dėtė',10,12,'- grąžina pasirinktus sužeistus draugiškus atgal į ranką.','/cards/inkvizicijos-legionas/CHARACTER_1-10.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-11','Tauricijus Amilas Gėtė',10,12,'- padaro','/cards/inkvizicijos-legionas/CHARACTER_1-11.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-12','Sesė Adriana',10,12,'- padaro -1','/cards/inkvizicijos-legionas/CHARACTER_1-12.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-13','Begnas Auksaspiegys',10,12,'- Suteikia po +1 draugiškiems','/cards/inkvizicijos-legionas/CHARACTER_1-13.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-14','Laukūnas Artibatis',10,12,'- atakuodamas padaro','/cards/inkvizicijos-legionas/CHARACTER_1-14.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-15','Bunikardas Vaga',10,12,'- su kitu Suteikia savo','/cards/inkvizicijos-legionas/CHARACTER_1-15.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-16','Taldas Giedragynis',10,12,NULL,'/cards/inkvizicijos-legionas/CHARACTER_1-16.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-17','Gerardas Malynas',10,12,NULL,'/cards/inkvizicijos-legionas/CHARACTER_1-17.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-18','Liucijus Dorys',10,12,NULL,'/cards/inkvizicijos-legionas/CHARACTER_1-18.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-19','Rimgaudas Servas',10,12,NULL,'/cards/inkvizicijos-legionas/CHARACTER_1-19.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-2','Baltramiejus Kelmas',10,12,'- iš rankos iškvieskite kurio kaina yra','/cards/inkvizicijos-legionas/CHARACTER_1-2.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-20','Birmantas Skribalis',10,12,NULL,'/cards/inkvizicijos-legionas/CHARACTER_1-20.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-21','Mundmantas Durpė',10,12,NULL,'/cards/inkvizicijos-legionas/CHARACTER_1-21.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-22','Inkvizicijos misionierius',10,12,NULL,'/cards/inkvizicijos-legionas/CHARACTER_1-22.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-23','Tumas Jonarijus',10,12,NULL,'/cards/inkvizicijos-legionas/CHARACTER_1-23.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-24','Indraris Varnas',10,12,'- Kiekvieno žaidėjo viršutinė kaladės korta yra atversta.','/cards/inkvizicijos-legionas/CHARACTER_1-24.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-3','Žemigijus Tolietis',10,12,'- kai ant šio tipo panaudojamas Traukite kortą. Galioja 1 kartą per ėjimą.','/cards/inkvizicijos-legionas/CHARACTER_1-3.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-4','Rogandas Maldinis',10,12,'- suteikia savo po +1 už kiekvieną, kovos lauke esantį, draugišką .','/cards/inkvizicijos-legionas/CHARACTER_1-4.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-5','Emilija Saulėtakė',10,12,'- Traukite 1 kortą.','/cards/inkvizicijos-legionas/CHARACTER_1-5.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-6','Dagnė Šviesnešė',10,12,'- suteikia','/cards/inkvizicijos-legionas/CHARACTER_1-6.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-7','Dolvydas Malda',10,12,'- Atlikęs puolimą įgyja +1','/cards/inkvizicijos-legionas/CHARACTER_1-7.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-8','Elmūras Milindzė',10,12,'- suteikia savo','/cards/inkvizicijos-legionas/CHARACTER_1-8.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1-9','Morisas Griaustinkalbis',10,12,'- suteikia savo','/cards/inkvizicijos-legionas/CHARACTER_1-9.webp','active',false),
('inkvizicijos-legionas/CHARACTER_1','Teodoras Ateljukas',10,12,'- iš rankos iškvieskite už ≤300','/cards/inkvizicijos-legionas/CHARACTER_1.webp','active',false),
('inkvizicijos-legionas/FIELD + Rarity-1','Mirties Pelkė',10,10,'Veikėjai su paskutinis noras miršta iš karto po iškvietimo.','/cards/inkvizicijos-legionas/FIELD%20%2B%20Rarity-1.webp','active',false),
('inkvizicijos-legionas/FIELD + Rarity','Užmirštųjų miškas',10,10,'- po sunaikinimo keliauja ne į kapiniyną o yra pašalinami iš žaidimo.','/cards/inkvizicijos-legionas/FIELD%20%2B%20Rarity.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_279','Inkvizitorius Madielius',10,12,'- draugiški tipo negali būti sunaikinti. Patyrę mirtiną žalą, lieka kovos lauke su 1 .','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_279.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_280','Inkvizitorius Liofanas',10,12,'- visiems draugiškiems suteikia +1 +1 ir . - ėjimo pradžioje suteikia +1 pasirinktam . +1','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_280.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_281','Elenora Kraujošviesa',10,12,'- Kai ant jos panaudojamas tipo padaro po -3 visiems priešininko .','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_281.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_282','Sieloras',10,12,'- suteikia savo - įgyja tiek + +5 kiek yra tavo kapinyne.','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_282.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_283','Šventasis raštas',10,12,'- tipo efektai veikia 2 kartus.','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_283.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_284','Dieviškoji aušra',10,12,'Atstato vistiems jūsų maksimalius +1 +1 jų taškus. Suteikia po už kiekvieną atstatytą gyvybės tašką.','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_284.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_285','Tėvas Konstancijus',10,12,'- kai draugiškas įgyja “Tėvas Konstancijus” įgyja +1 +1','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_285.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_286','Šventoji ranka',10,12,'Suteikia visiems draugiškiems +2 +2','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_286.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_287','Albas Griaustinskydis',10,12,'- suteikia visiems sužeistiems, draugiškiems','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_287.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_288','Gydantis žibintas',10,12,'Suteikia visiems draugiškiems +3 ir','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_288.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_289','Pranašo kryžius',10,12,'- ėjimo pradžioje suteikia +3 pasirinktam draugiškam','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_289.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_290','Bažnyčios šauklys',10,12,'- visiems draugiškiems tipo suteikia +1','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_290.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-1','Šventasis išvalymas',10,12,'. Sunaikina pasirinktą Suteikia tavo','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-1.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-10','Atsitraukimas',10,12,'Sugrąžina vieną savo Ir suteikia jam į ranką kitą kartą jį iškvietus į kovos lauką.','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-10.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-11','Apvaizda',10,12,'Traukite 2 kortas.','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-11.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-12','Pranašystė',10,12,'Pažiūrėk į priešininkų kortas.','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-12.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-2','Šventieji skaitiniai',10,12,'Traukite 2 kortas.','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-2.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-3','Šventasis skydas',10,12,'suteikia +2 Pasirinktam +2 ir','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-3.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-4','Šviesos palaiminimas',10,12,'Suteikia pasirinktam','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-4.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-5','Šventasis įkvėpimas',10,12,'Suteikia pasirinktam +3 +3 .','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-5.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-6','Šventintas vanduo',10,12,'Suteikia savo su','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-6.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-7','Angeliškas švytėjimas',10,12,'Pasirinktam','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-7.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-8','Šventoji rykštė',10,12,'Visiems priešininko padaro po -3','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-8.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291-9','Inkvizitoriaus Išmintis',10,12,'Suteikia po +2 draugiškiems','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291-9.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_291','Angeliška apsauga',10,12,'Suteikia visiems tipo esantiems kovos lauke','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_291.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_292','Inkvizicijos riteris',10,12,'- Kai ant jo panaudojamas tipo papildomai įgyja +1','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_292.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_293-1','Vilijus Morifadzė',10,12,'- kai draugiškas jį igyja ir šis','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_293-1.webp','active',false),
('inkvizicijos-legionas/Inkvizicijos_legionas_293','Klemensas Hilgardas',10,12,'-2 - padaro priešininko o savo','/cards/inkvizicijos-legionas/Inkvizicijos_legionas_293.webp','active',false),
('mirties-marsas/ARTIFACT-1','Nakties vėjų kompasas',6,11,'- ėjimo pradžioje išsirinkite 1 kortą iš kapinyno ir įmaišykite ją atgal į kaladę.','/cards/mirties-marsas/ARTIFACT-1.webp','active',false),
('mirties-marsas/ARTIFACT-2','Nekromanto amuletas',6,11,'- visi sunaikinti keliauja ne į kapinyną, o įmaišomi atgal į kaladę.','/cards/mirties-marsas/ARTIFACT-2.webp','active',false),
('mirties-marsas/ARTIFACT','Kapinių žibintas',6,11,'- visiems iš kapinyno prikeltiems +2 suteikia +2 .','/cards/mirties-marsas/ARTIFACT.webp','active',false),
('mirties-marsas/CHAMPIOIN_Phase_1','Prazaras I-masis',6,9,'12 Iškviečia “Zombis” iš kaladės, rankos arba arba kapinyno. Sunaikina draugišką sau +2 Visi draugiški +1 +1','/cards/mirties-marsas/CHAMPIOIN_Phase_1.webp','active',true),
('mirties-marsas/CHAMPIOIN_Phase_2','Prazaras I-masis',6,9,'15 Iškviečia 2 “Zombis” iš kaladės, rankos arba arba kapinyno. Sunaikina draugišką sau +4 Visi draugiški +2 +2','/cards/mirties-marsas/CHAMPIOIN_Phase_2.webp','active',true),
('mirties-marsas/CHAMPIOIN_Phase_3','Prazaras I-masis',6,9,'19 Iškviečia 4 “Zombis” iš kaladės, rankos arba arba kapinyno. Sunaikina draugišką sau +6 Visi draugiški +3 +3','/cards/mirties-marsas/CHAMPIOIN_Phase_3.webp','active',true),
('mirties-marsas/CHARACTER_1-1','Malduras Juodasis',6,12,'- kai puola priešininko kapinyno į kovos lauką iškviečiamas 1 pasirinktas','/cards/mirties-marsas/CHARACTER_1-1.webp','active',false),
('mirties-marsas/CHARACTER_1-10','Maro juokdarys',6,12,'-2 - grįžta į kovos lauką, su -2 Efektas galioja tik vieną kartą per žaidimą.','/cards/mirties-marsas/CHARACTER_1-10.webp','active',false),
('mirties-marsas/CHARACTER_1-11','Kaulų rinkėjas',6,12,'- visi sunaikinti tavo keliauja ne į kapinyną, o įmaišomi atgal į kaladę.','/cards/mirties-marsas/CHARACTER_1-11.webp','active',false),
('mirties-marsas/CHARACTER_1-12','Pagiežingasis Fenrikas',6,12,'- tik puolimo metu įgyja +1 už kiekvieną kovos lauke esantį priešininko','/cards/mirties-marsas/CHARACTER_1-12.webp','active',false),
('mirties-marsas/CHARACTER_1-13','Vėlių šauklė',6,12,'- iškviečia pasirinktą tipo iš kapinyno į kovos lauką. Jo kaina ≤200','/cards/mirties-marsas/CHARACTER_1-13.webp','active',false),
('mirties-marsas/CHARACTER_1-14','Anera Pūvančioji',6,12,'- traukite kortą.','/cards/mirties-marsas/CHARACTER_1-14.webp','active',false),
('mirties-marsas/CHARACTER_1-15','Belmoras Žiaurusis',6,12,'- padaro -2 pasirinktam .','/cards/mirties-marsas/CHARACTER_1-15.webp','active',false),
('mirties-marsas/CHARACTER_1-16','Zombis pranašas',6,12,'- traukite 2 kortas.','/cards/mirties-marsas/CHARACTER_1-16.webp','active',false),
('mirties-marsas/CHARACTER_1-17','Skausmo šauklys',6,12,'- Gali būti iškviestas vietoje “Zombis”.','/cards/mirties-marsas/CHARACTER_1-17.webp','active',false),
('mirties-marsas/CHARACTER_1-18','Mirties šamanė',6,12,'- pasirinktam +2 suteikia .','/cards/mirties-marsas/CHARACTER_1-18.webp','active',false),
('mirties-marsas/CHARACTER_1-19','Dr. Krudžas',6,12,'- pasirinktam suteikia +1','/cards/mirties-marsas/CHARACTER_1-19.webp','active',false),
('mirties-marsas/CHARACTER_1-2','Nekrobaronas Izmoris',6,12,'- kai panaudojamas tipo kapinyno į kovos lauką iškviečiamas 1 pasirinktas','/cards/mirties-marsas/CHARACTER_1-2.webp','active',false),
('mirties-marsas/CHARACTER_1-20','Zombis golemas',6,12,'- padaro po -3 pasirinktiems','/cards/mirties-marsas/CHARACTER_1-20.webp','active',false),
('mirties-marsas/CHARACTER_1-21','Kūnų draskytojas',6,12,NULL,'/cards/mirties-marsas/CHARACTER_1-21.webp','active',false),
('mirties-marsas/CHARACTER_1-22','Šešėlių šmėkla',6,12,NULL,'/cards/mirties-marsas/CHARACTER_1-22.webp','active',false),
('mirties-marsas/CHARACTER_1-23','Zombis klajoklis',6,12,NULL,'/cards/mirties-marsas/CHARACTER_1-23.webp','active',false),
('mirties-marsas/CHARACTER_1-24','Kapinyno bastūnas',6,12,NULL,'/cards/mirties-marsas/CHARACTER_1-24.webp','active',false),
('mirties-marsas/CHARACTER_1-25','Nakties tarnas',6,12,'- pasirinktam','/cards/mirties-marsas/CHARACTER_1-25.webp','active',false),
('mirties-marsas/CHARACTER_1-26','Kapinių vagis',6,12,'- išmaišyk kapinyną ir aklai trauk vieną kortą.','/cards/mirties-marsas/CHARACTER_1-26.webp','active',false),
('mirties-marsas/CHARACTER_1-27','Maro karys',6,12,'- darydamas žalą padaro','/cards/mirties-marsas/CHARACTER_1-27.webp','active',false),
('mirties-marsas/CHARACTER_1-28','Šmėkla klajoklė',6,12,'- atversk viršutinę kaladės kortą ir parodyk ją priešininkui.','/cards/mirties-marsas/CHARACTER_1-28.webp','active',false),
('mirties-marsas/CHARACTER_1-29','Kūnų rijikas',6,12,'- gali atakuoti tik','/cards/mirties-marsas/CHARACTER_1-29.webp','active',false),
('mirties-marsas/CHARACTER_1-3','Vergvaldys Zaragas',6,12,'- kai iš kapinyno prikeliamas “Vergvaldys Zaragas” įgija +2 +2 .','/cards/mirties-marsas/CHARACTER_1-3.webp','active',false),
('mirties-marsas/CHARACTER_1-30','Zombis kariškis',6,12,'- keliauja priešininkui į rankas.','/cards/mirties-marsas/CHARACTER_1-30.webp','active',false),
('mirties-marsas/CHARACTER_1-31','Nutrūktgalvis Benis',6,12,'- išmesk 1 savo kortą nuo kaladės viršaus į kapinyną.','/cards/mirties-marsas/CHARACTER_1-31.webp','active',false),
('mirties-marsas/CHARACTER_1-32','Anabolinis zombis',6,12,NULL,'/cards/mirties-marsas/CHARACTER_1-32.webp','active',false),
('mirties-marsas/CHARACTER_1-33','Zombis',6,12,NULL,'/cards/mirties-marsas/CHARACTER_1-33.webp','active',false),
('mirties-marsas/CHARACTER_1-34','Kapinių nekromantas',6,12,'- iškviečia 2 “Zombis” iš kaladės rankos arba kapinyno.','/cards/mirties-marsas/CHARACTER_1-34.webp','active',false),
('mirties-marsas/CHARACTER_1-35','Ramturas prakeiktasis',6,12,'- Kai tavo sunaikinamas į jo vietą iškviesk “Zombis” iš kaladės rankos arba kapinyno. Suteik jam .','/cards/mirties-marsas/CHARACTER_1-35.webp','active',false),
('mirties-marsas/CHARACTER_1-4','Zordakas Brutalusis',6,12,'- Gali būti iškviestas vietoje “Zombis”.','/cards/mirties-marsas/CHARACTER_1-4.webp','active',false),
('mirties-marsas/CHARACTER_1-5','Zordakas Brutalusis',6,12,'- Gali būti iškviestas vietoje “Zombis”.','/cards/mirties-marsas/CHARACTER_1-5.webp','active',false),
('mirties-marsas/CHARACTER_1-6','Eldoras sielų meistras',6,12,'- visi +2 tipo įgyja +2 .','/cards/mirties-marsas/CHARACTER_1-6.webp','active',false),
('mirties-marsas/CHARACTER_1-7','Bišopas Argalurdas',6,12,'- kas kartą iškvietus tipo į kovos lauką, traukite kortą.','/cards/mirties-marsas/CHARACTER_1-7.webp','active',false),
('mirties-marsas/CHARACTER_1-8','Pranašas Draumoras',6,12,'- Kiekvieno ėjimo pradžioje iškviečia 2 “Skeletas”.','/cards/mirties-marsas/CHARACTER_1-8.webp','active',false),
('mirties-marsas/CHARACTER_1-9','Sargonas Kraugerys',6,12,'- prieš puldamas priešininko įgyja +2','/cards/mirties-marsas/CHARACTER_1-9.webp','active',false),
('mirties-marsas/CHARACTER_1','Mirties baronė Vaela',6,12,'- savo ėjimo pradžioje, iš kapinyno į kovos lauką iškviečiamas 1 pasirinktas','/cards/mirties-marsas/CHARACTER_1.webp','active',false),
('mirties-marsas/CHARACTER_2-1','Išprotėjas nekromantas',6,12,'- iš kaladės, rankos arba kapinyno į kovos lauką iškviečiamas “Zombis”.','/cards/mirties-marsas/CHARACTER_2-1.webp','active',false),
('mirties-marsas/CHARACTER_2-2','Zanara Tamsioji',6,12,NULL,'/cards/mirties-marsas/CHARACTER_2-2.webp','active',false),
('mirties-marsas/CHARACTER_2-3','Kapinių ragana',6,12,NULL,'/cards/mirties-marsas/CHARACTER_2-3.webp','active',false),
('mirties-marsas/CHARACTER_2-4','Zombis sargas',6,12,NULL,'/cards/mirties-marsas/CHARACTER_2-4.webp','active',false),
('mirties-marsas/CHARACTER_2-5','Skeletas',6,12,'- Savo ėjimo pabaigoje sunaikinamas.','/cards/mirties-marsas/CHARACTER_2-5.webp','active',false),
('mirties-marsas/CHARACTER_2','Varinas kapų gynėjas',6,12,'- iš kaladės, rankos arba kapinyno iškvieskite “Zombis klajoklis”.','/cards/mirties-marsas/CHARACTER_2.webp','active',false),
('mirties-marsas/FIELD + Rarity-1','Platusus laukas',6,10,'- Padidina vietų skaičių nuo 5 iki 10 kiekvienoje pusėje.','/cards/mirties-marsas/FIELD%20%2B%20Rarity-1.webp','active',false),
('mirties-marsas/FIELD + Rarity','Mirties Pelkė',6,10,'- Visi su sunaikinami iš karto po iškvietimo.','/cards/mirties-marsas/FIELD%20%2B%20Rarity.webp','active',false),
('mistikos-melodija/FIELD + Rarity-1','Mirties Pelkė',12,10,'Veikėjai su paskutinis noras miršta iš karto po iškvietimo.','/cards/mistikos-melodija/FIELD%20%2B%20Rarity-1.webp','active',false),
('mistikos-melodija/FIELD + Rarity','Tylos katedra',12,10,'- visi','/cards/mistikos-melodija/FIELD%20%2B%20Rarity.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_117','Elvira Melvija',12,12,'- padidina visų tavo ir žalą +3 . - pasirinkite tris kortas iš kapinyno ir įmaišykite jas į kaladę.','/cards/mistikos-melodija/Mistikos_Melodija_117.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_118','Lindara Vingrė',12,12,'- šį ėjimą iš rankos galite nemokamai panaudoti 1 kortą. - padidina visų tavo ir žalą +2 .','/cards/mistikos-melodija/Mistikos_Melodija_118.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_119','Serina Ilyra',12,12,'- priešininkui iškvietus suteikia tavo','/cards/mistikos-melodija/Mistikos_Melodija_119.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_120','Valtoras Magninis',12,12,'- pasirink vieną iš savo kapinyno, grąžink jį į ranką. - po panaudojimo šis patiria -3 grįžta atgal į ranką.','/cards/mistikos-melodija/Mistikos_Melodija_120.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_121','Atgalinis smūgis',12,12,'Aktyvuojasi, priešininkui puolant Puolantis sunaikinamas, o jo padaryta žala grįžta puolančiam .','/cards/mistikos-melodija/Mistikos_Melodija_121.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_122','Alchemikų fortas',12,12,'- Panaudojus jis grįžta atgal į kaladę.','/cards/mistikos-melodija/Mistikos_Melodija_122.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_123','Sprogstanti magija',12,12,'Aktyvuojasi, kai priešininkas panaudoja . Padaro po -4 visiems priešininko ir .','/cards/mistikos-melodija/Mistikos_Melodija_123.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_124','Gydūnė Džilė',12,12,'- jums panaudojus bet kokį arba to - pagydykite savo arba','/cards/mistikos-melodija/Mistikos_Melodija_124.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_125','Tvirbutis Mirka',12,12,'- padaro -4 pasirinktam','/cards/mistikos-melodija/Mistikos_Melodija_125.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_126','Archidija Zapora',12,12,'- padaro visiems kovos lauke.','/cards/mistikos-melodija/Mistikos_Melodija_126.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_127','Magiškas portalas',12,12,'- Kai panaudoji trauk papildomą kortą.','/cards/mistikos-melodija/Mistikos_Melodija_127.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_128','Jorūnė Tamsa',12,12,'- sunaikina 1 aklai pasirinktą priešininko kortą iš jo rankos.','/cards/mistikos-melodija/Mistikos_Melodija_128.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_129','Lindara Šilė',12,12,'- padaro priešininko','/cards/mistikos-melodija/Mistikos_Melodija_129.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_130','Bandos jausmas',12,12,'Aktyvuojasi, kai priešininkas puola jūsų 2 iš kovos lauko pasirinkite ir grąžinkite juos į ranką.','/cards/mistikos-melodija/Mistikos_Melodija_130.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_131','Apokaliptinė audra',12,12,'Padaro visiems lauke -6 ir . Visi likę gyvi kovos ir grįžta į ranką.','/cards/mistikos-melodija/Mistikos_Melodija_131.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_132','Edmundas Žvarba',12,12,'- padaro vienam pasirinktam -2','/cards/mistikos-melodija/Mistikos_Melodija_132.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_133','Laumės kerštas',12,12,'Priešininkui sunaikinus jūsų visi priešininko po -3 ir , patiria .','/cards/mistikos-melodija/Mistikos_Melodija_133.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_134','Didysis Edidalfas',12,12,'- traukite kortas tol, kol rankoje turėsite 4 kortas.','/cards/mistikos-melodija/Mistikos_Melodija_134.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_135','Zefiksas Kulternis',12,12,'- sunaikinkite 1 pasirinktą priešininko','/cards/mistikos-melodija/Mistikos_Melodija_135.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_136','Kamuolinis žaibas',12,12,'Padaro -3 , arba ir pasirinktam . jei taikinys sunaikinamas. Padaro -3 ir antram pasirinktam taikiniui.','/cards/mistikos-melodija/Mistikos_Melodija_136.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_137','Selma Zylė',12,12,'- Pašalinkite vieną -1 žalos modifikatorių iš savo kaladės iki žaidimo pabaigos.','/cards/mistikos-melodija/Mistikos_Melodija_137.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_138','Speigo lazda',12,12,'- ėjimo pradžioje galite pasirinktą sužeistą','/cards/mistikos-melodija/Mistikos_Melodija_138.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_139','Gynybinė aura',12,12,'Aktyvuojasi priešininkui puolant jūsų Sumažina žalą per pusę, patiriamą žalą apvalinant į didesnę pusę.','/cards/mistikos-melodija/Mistikos_Melodija_139.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_140','Fabijus Kintis',12,12,'- padaro -2 arba pasirinktam jei jis lieka gyvas grąžiną jį į ranką.','/cards/mistikos-melodija/Mistikos_Melodija_140.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_141','Stichijų skydas',12,12,'Aktyvuojasi priešininkui panaudojus kortą, anuliuoja jos poveikį. Jūs traukiate kortą.','/cards/mistikos-melodija/Mistikos_Melodija_141.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_142','Narmintas Žvabris',12,12,'- kai panaudojate įgyja +1','/cards/mistikos-melodija/Mistikos_Melodija_142.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_143','Paslėpta galia',12,12,'Aktyvuojasi, kai jūsų yra atakuojamas. Puolantysis patiria -3','/cards/mistikos-melodija/Mistikos_Melodija_143.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_144','Elementų kamuoliai',12,12,'Padaro -4 , dviems pasirinktiems arba -6','/cards/mistikos-melodija/Mistikos_Melodija_144.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_145','Eustachijus Silas',12,12,'- kai panaudojate Padarykite tipo , tam pačiam taikiniui.','/cards/mistikos-melodija/Mistikos_Melodija_145.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_146','Germundas Dringis',12,12,'- Padidina žalą +2','/cards/mistikos-melodija/Mistikos_Melodija_146.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_147','Milva Sarvilė',12,12,'- suteikia kortą. Traukite kortas tol, kol rasite kortą. Kitas kortas įmaišykite atgal.','/cards/mistikos-melodija/Mistikos_Melodija_147.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_148','Stingdantis kristalas',12,12,'Padaro -3 ir pasirinktam .','/cards/mistikos-melodija/Mistikos_Melodija_148.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_149','Liepsnos liežuviai',12,12,'Aktyvuojasi priešininkui iškviečiant . Padaro jam -6 , Visa perteklinė žala padaroma priešininko .','/cards/mistikos-melodija/Mistikos_Melodija_149.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_150','Ugnies kamuolys',12,12,'Padaro -6 , ,','/cards/mistikos-melodija/Mistikos_Melodija_150.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_151','Tornadas',12,12,'Padaro visiems priešininko , ,','/cards/mistikos-melodija/Mistikos_Melodija_151.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_152','Ilfas Kintas',12,12,'- padidina tavo žalą +1','/cards/mistikos-melodija/Mistikos_Melodija_152.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_153','Markas Žalvarnis',12,12,'- traukite kortą.','/cards/mistikos-melodija/Mistikos_Melodija_153.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_154','Servina Sidabrė',12,12,'- padidina tavo žalą +1','/cards/mistikos-melodija/Mistikos_Melodija_154.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_155','Benediktas Rūkas',12,12,'- traukite kortą.','/cards/mistikos-melodija/Mistikos_Melodija_155.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_156','Branas Vėjūnas',12,12,'- padaro','/cards/mistikos-melodija/Mistikos_Melodija_156.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_157','Magiški atradimai',12,12,'Įmaišykite 2 pasirinktas kortas iš rankos atgal į kaladę, išmaišykite ir traukite 3 kortas.','/cards/mistikos-melodija/Mistikos_Melodija_157.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_158','Sapnų kerai',12,12,'Grąžinkite pasirinktą atgal į ranką. Traukite kortą.','/cards/mistikos-melodija/Mistikos_Melodija_158.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_159','Vilnė Saulinė',12,12,NULL,'/cards/mistikos-melodija/Mistikos_Melodija_159.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_160','Sekinančios stichijos',12,12,'Padaro visiems -2 -2','/cards/mistikos-melodija/Mistikos_Melodija_160.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_161','Kerų atsiskleidimas',12,12,'Aktyvuojasi, kai priešininkas iškviečia . Suteikia jūsų pasirinktam +3 +3 .','/cards/mistikos-melodija/Mistikos_Melodija_161.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_162','Ugnies pliūpsnis',12,12,'Padaro -2 pasirinktam .','/cards/mistikos-melodija/Mistikos_Melodija_162.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_163','Žaibo iškrova',12,12,'Padaro -1 pasirinktam ir dviems šalia esantiems','/cards/mistikos-melodija/Mistikos_Melodija_163.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_164','Salivija Zilda',12,12,NULL,'/cards/mistikos-melodija/Mistikos_Melodija_164.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_165','Milfredas Senasis',12,12,'- tavo palankiai naudoja žalos modifikatorius.','/cards/mistikos-melodija/Mistikos_Melodija_165.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_166','Aptikti magiją',12,12,'- suteikia kortą. Traukite kortas tol, kol rasite','/cards/mistikos-melodija/Mistikos_Melodija_166.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_167','Naujos žinios',12,12,'Traukite 2 kortas.','/cards/mistikos-melodija/Mistikos_Melodija_167.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_168','Noras Tamietis',12,12,'- atakuodamas padaro ir','/cards/mistikos-melodija/Mistikos_Melodija_168.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_169','Tylos!',12,12,'Aktyvuojasi priešininkui panaudojus','/cards/mistikos-melodija/Mistikos_Melodija_169.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_170','Gurvydas Grifas',12,12,NULL,'/cards/mistikos-melodija/Mistikos_Melodija_170.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_171','Žaibmantas Lakasūnas',12,12,NULL,'/cards/mistikos-melodija/Mistikos_Melodija_171.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_172','Archimagas Lisarijus',12,12,'šį ėjimą kainuos -100 Kitas 12 pigiau. Padaro -4 arba pasirinktam , . Padaro','/cards/mistikos-melodija/Mistikos_Melodija_172.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_173','Archimagas Lisarijus',12,12,'šį ėjimą kainuos -200 Kitas 15 pigiau. Padaro -6 arba pasirinktam , . Padaro visiems Priešininko','/cards/mistikos-melodija/Mistikos_Melodija_173.webp','active',false),
('mistikos-melodija/Mistikos_Melodija_174','Archimagas Lisarijus',12,12,'šį ėjimą kainuos -300 Kitas 19 pigiau. Padaro -8 arba pasirinktam , . Padaro visiems Priešininko','/cards/mistikos-melodija/Mistikos_Melodija_174.webp','active',false),
('plesiku-naktis/FIELD + Rarity-1','Siauras skersgatvis',7,10,'- Kiekvienas savo ėjimo metu gali atakuoti tik su dviem','/cards/plesiku-naktis/FIELD%20%2B%20Rarity-1.webp','active',false),
('plesiku-naktis/FIELD + Rarity','Vėjų uostas',7,10,'- Kiekvieno ėjimo pradžioje priešininkas pasirenka 1 ir grąžina jį į ranką.','/cards/plesiku-naktis/FIELD%20%2B%20Rarity.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_100','Laivo apskaita',7,12,'Šį ėjimą visos kortos kainuoja -100 100 pigiau. Bet ne mažiau nei .','/cards/plesiku-naktis/Plesiku_Naktis_100.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_101','Gluodas Gilunis',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_101.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_102','Mirtulė Aura',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_102.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_103','Lutis Dolcas',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_103.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_104','Dargis Ištras',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_104.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_105','Gelgaudas Audra',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_105.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_106','Piratas Marodierius',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_106.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_107','Belmontas Semas',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_107.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_108','Egzekucija',7,12,'Sunaikina pasirinktą sužeistą','/cards/plesiku-naktis/Plesiku_Naktis_108.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_109','Piratas raitelis',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_109.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_110','Kuršas Žaibas',7,12,'- kai sunaikina priešininko visiems kitiems priešininko padaro','/cards/plesiku-naktis/Plesiku_Naktis_110.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_111','Piratas žvalgas',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_111.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_112','Leisk man!',7,12,'vieną kartą gali pulti tiesiogiai padarydamas -4 Tačiau gauna atgalinę žalą.','/cards/plesiku-naktis/Plesiku_Naktis_112.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_113','Pirmyn!',7,12,'Suteikia pasirinktam ir +2 .','/cards/plesiku-naktis/Plesiku_Naktis_113.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_114','Kapitonas Juodasmakris',7,12,'Suteikia tau +100 Paaukok -200 12 šiam ėjimui. ir padaryk -4 pasirinktam . Sunaikina pasirinktą priešininko jei jis turi ≤2 .','/cards/plesiku-naktis/Plesiku_Naktis_114.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_115','Kapitonas Juodasmakris',7,12,'Suteikia tau +200 Paaukok -300 15 šiam ėjimui. ir padaryk -6 pasirinktam . Sunaikina pasirinktą priešininko jei jis turi ≤3 .','/cards/plesiku-naktis/Plesiku_Naktis_115.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_116','Kapitonas Juodasmakris',7,12,'Suteikia tau +300 Paaukok -400 19 šiam ėjimui. ir padaryk -8 pasirinktam . Sunaikina pasirinktą priešininko jei jis turi ≤4 .','/cards/plesiku-naktis/Plesiku_Naktis_116.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_59','Svantonas Lazaras',7,12,'- priešininko ėjimo pradžioje iš jo pavagia -200 sau +1','/cards/plesiku-naktis/Plesiku_Naktis_59.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_60','Prakeiktasis Džimis',7,12,'- sunaikinti draugiški tipo keliauja ne į kapinyną o į kaladės apačią.','/cards/plesiku-naktis/Plesiku_Naktis_60.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_61','Liucijus Marikas',7,12,'- Padaro visiems kurie jį atakuoja.','/cards/plesiku-naktis/Plesiku_Naktis_61.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_62','Morganas Greivsas',7,12,'- Sunaikina pasirinktą iki ėjimo pabaigos suteikia jo taškus sau.','/cards/plesiku-naktis/Plesiku_Naktis_62.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_63','Grizmas Šmėklinis',7,12,'- padaro -2 arba pasirinktam Jei jis sunaikinamas, šiam ėjimui gaunate +100','/cards/plesiku-naktis/Plesiku_Naktis_63.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_64','Žiežarė Varnė',7,12,'- priešininko ėjimo pradžioje iš jo pavagia -100 . Draugiški kas kartą traukia po kortą.','/cards/plesiku-naktis/Plesiku_Naktis_64.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_65','Juodmūšis Žiaurusis',7,12,'- suteikia +100 ir kortos traukimą. - suteikia kortos taukimą.','/cards/plesiku-naktis/Plesiku_Naktis_65.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_66','Kapitonas Juodragis',7,12,'- kai šis padaro žalą kitam traukite kortą. - visi','/cards/plesiku-naktis/Plesiku_Naktis_66.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_67','Krofordas Rūstusis',7,12,'- Sunaikina pasirinktą arba .','/cards/plesiku-naktis/Plesiku_Naktis_67.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_68','Saimonas Goldinis',7,12,'- išmesk iki 3 viršutinių savo kaladės kortų į kapinyną, už kiekvieną gauk +200','/cards/plesiku-naktis/Plesiku_Naktis_68.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_69','Kapitono Teleskopas',7,12,'- Priešininkų kainuoja +100 -100 iškvietimas brangiau, jūsų pigiau.','/cards/plesiku-naktis/Plesiku_Naktis_69.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_70','Kapitono Paslaptis',7,12,'Traukite 2 kortas, jeigu neturite kovos lauke, įgykite +200','/cards/plesiku-naktis/Plesiku_Naktis_70.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_71','Kulvinas Kirvarža',7,12,'- kai puola priešininko suteikia savo','/cards/plesiku-naktis/Plesiku_Naktis_71.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_72','Griausminė Grikštė',7,12,'- tavo žalos modifikatoriai -1 veikia kaip +1','/cards/plesiku-naktis/Plesiku_Naktis_72.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_73','Elė Kapitono padejėja',7,12,'- jei kaladėje arba rankoje turite “Munčis chebrantas” iškvieskite jį į kovos lauką.','/cards/plesiku-naktis/Plesiku_Naktis_73.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_74','Baltvilis Žiaurusis',7,12,'- Kai šis įgauna +3','/cards/plesiku-naktis/Plesiku_Naktis_74.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_75','Krofordo relikvijos',7,12,'Visiems suteikia tipo +1 +1 kovos lauke, . - “Krofordas Rūstusis” suteikia +2 +2','/cards/plesiku-naktis/Plesiku_Naktis_75.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_76','Prakeiktas auksas',7,12,'Padaro -1 visiems kovos lauke, Už kiekvieną paveiktą suteikia savo tau +100','/cards/plesiku-naktis/Plesiku_Naktis_76.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_77','Gylis Paslaptingasis',7,12,'- kai pavagiamos monetos įgyja +2 ir','/cards/plesiku-naktis/Plesiku_Naktis_77.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_78','Tomis Svyids',7,12,'- tavo žalos modifikatoriai +2 veikia kaip x2','/cards/plesiku-naktis/Plesiku_Naktis_78.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_79','Rūskė Aidė',7,12,'- suteikia +100 , traukite kortą.','/cards/plesiku-naktis/Plesiku_Naktis_79.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_80','Barbadosas Klintas',7,12,'- ėjimo pradžioje gaukite papildomus +100','/cards/plesiku-naktis/Plesiku_Naktis_80.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_81','Paslaptinga skrynelė',7,12,'- suteikia +200 arba kortos traukimą.','/cards/plesiku-naktis/Plesiku_Naktis_81.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_82','Jūros šmėklos lobis',7,12,'Suteikia visiems +200 jų sekančio ėjimo pradžioje. Visiems kovos lauke padaro','/cards/plesiku-naktis/Plesiku_Naktis_82.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_83','Vilkė Šėlsminė',7,12,'- jei kaladėje arba rankoje turite “Mirtulė Aura” iškvieskite ją į kovos lauką.','/cards/plesiku-naktis/Plesiku_Naktis_83.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_84','Jungos agonija',7,12,'Suteikia +5 tipo','/cards/plesiku-naktis/Plesiku_Naktis_84.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_85','Drūzas Kirvarža',7,12,'- visų priešininko iškvietimas kainuoja +100','/cards/plesiku-naktis/Plesiku_Naktis_85.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_86','Netikėtos relikvijos',7,12,'Suteikia visiems draugiškiems +2 Visiems priešininkų +1 iki tavo ėjimo pabaigos.','/cards/plesiku-naktis/Plesiku_Naktis_86.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_87','Žėltma Šarmė',7,12,'- Kai patiria žalą, suteikia pasirinktam draugiškam','/cards/plesiku-naktis/Plesiku_Naktis_87.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_88','Grobio dalybos',7,12,'Suteikia visiems po +300 jų sekančio ėjimo pradžioje.','/cards/plesiku-naktis/Plesiku_Naktis_88.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_89','Juodvėrė Mirla',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_89.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_90','Azura Miklioji',7,12,'- Atlikus puolimo veiksmą grįžta atgal į ranką.','/cards/plesiku-naktis/Plesiku_Naktis_90.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_91','Vilpūras Semis',7,12,'- iš kaladės trauk 2 kortas.','/cards/plesiku-naktis/Plesiku_Naktis_91.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_92','Munčis chebrantas',7,12,'- jei kaladėje arba rankoje turite “Piratas žvalgas” iškvieskite jį į kovos lauką.','/cards/plesiku-naktis/Plesiku_Naktis_92.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_93','Žaibo Plunksna',7,12,'- padaro visiems priešininkų po -3','/cards/plesiku-naktis/Plesiku_Naktis_93.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_94','Staugirdas Klasta',7,12,'- ėjimo pradžioje gaukite +100 .','/cards/plesiku-naktis/Plesiku_Naktis_94.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_95','Jungos plunksna',7,12,'- visi tavo žalos modifikatoriai įgyja +1','/cards/plesiku-naktis/Plesiku_Naktis_95.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_96','Smakas Klampynas',7,12,'- ateinantį savo ėjimą priešininkas netenka -100','/cards/plesiku-naktis/Plesiku_Naktis_96.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_97','Kapitonas Kernis',7,12,'- kitam +2 tipo suteikia .','/cards/plesiku-naktis/Plesiku_Naktis_97.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_98','Irga Įžūlė',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_98.webp','active',false),
('plesiku-naktis/Plesiku_Naktis_99','Apsukrusis Drakšlys',7,12,NULL,'/cards/plesiku-naktis/Plesiku_Naktis_99.webp','active',false),
('sviesos-pulkas/FIELD + Rarity-1','Ginklų sandėlis',11,10,'- Visi','/cards/sviesos-pulkas/FIELD%20%2B%20Rarity-1.webp','active',false),
('sviesos-pulkas/FIELD + Rarity','Gynybiniai įtvirtinimai',11,10,'- Kol puisėje yra bent 1 tas negali būti atakos taikinys.','/cards/sviesos-pulkas/FIELD%20%2B%20Rarity.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_233','Gunteris Narsusis',11,12,'- įgyja po +2 priešininko','/cards/sviesos-pulkas/Sviesos_Pulkas_233.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_234','Alarikas Teisusis',11,12,'- suteikia visiems draugiškiems po +1','/cards/sviesos-pulkas/Sviesos_Pulkas_234.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_235','Magnusas Justinijus',11,12,'- priešininkui panaudojus sunaikina aklai pasirinktą priešininko kortą iš rankos.','/cards/sviesos-pulkas/Sviesos_Pulkas_235.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_236','Doriana Ugningoji',11,12,'- Sunaikina po 1 tavo pasirinktą abejuose kovos lauko pusėse. Už kiekvieną įgyja +3','/cards/sviesos-pulkas/Sviesos_Pulkas_236.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_237','Garbingasis Ulbas',11,12,'- Kai sunaikina priešininko suteikia +2 pasirinktam','/cards/sviesos-pulkas/Sviesos_Pulkas_237.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_238-1','Šviesos sargybinis',11,12,'- ėjimo pradžioje, suteikia +1 pasirinktam','/cards/sviesos-pulkas/Sviesos_Pulkas_238-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_238','Seras Goldbergeris',11,12,'- Pasirinktas draugiškas maksimaliai gali patirti 3 per ataką.','/cards/sviesos-pulkas/Sviesos_Pulkas_238.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_239','Kapitonas Arnulfas',11,12,'- Kai puolantis priešininko sunaikinamas, draugiški įgyja +1','/cards/sviesos-pulkas/Sviesos_Pulkas_239.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_240-1','Matihilda',11,12,'- traukite kortą, jei ištraukėte su iškvieskite jį į kovos lauką.','/cards/sviesos-pulkas/Sviesos_Pulkas_240-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_240','Bernardas Gynėjas',11,12,'- su draugišku Gynėjas” įgyja +2','/cards/sviesos-pulkas/Sviesos_Pulkas_240.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_241-1','Kontrpuolimas',11,12,'Visi sužeisti, draugiški kovos lauke, šį ėjimą gali atakuoti priešininko du kartus.','/cards/sviesos-pulkas/Sviesos_Pulkas_241-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_241','Ordino apsuptis',11,12,'Visi priešininko po -2 ir patiria . Sekantį ėjimą, priešininkas negali atakuoti.','/cards/sviesos-pulkas/Sviesos_Pulkas_241.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_242-1','Stiprus užnugaris',11,12,'Dviems kovos lauke suteikia +2 . +2','/cards/sviesos-pulkas/Sviesos_Pulkas_242-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_242','Mergelė Liliana',11,12,'- Traukiant kortą suteikia visiems tavo','/cards/sviesos-pulkas/Sviesos_Pulkas_242.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_243-1','Įšventinimo kalavijas',11,12,'- Kai sunaikinamas tavo su tavo','/cards/sviesos-pulkas/Sviesos_Pulkas_243-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_243','Garbės priesaika',11,12,'Suteikia vienam','/cards/sviesos-pulkas/Sviesos_Pulkas_243.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_244','Seras Hoftmanas',11,12,'- iškviečia 2 “Riteris” iš kaladės arba rankos.','/cards/sviesos-pulkas/Sviesos_Pulkas_244.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_245','Generolas Budolfas',11,12,'- iškviečia vertė yra ≤400','/cards/sviesos-pulkas/Sviesos_Pulkas_245.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_246','Heilderbergo bokštas',11,12,'- Kai atakuojamas tavo su padaro -1 priešininko','/cards/sviesos-pulkas/Sviesos_Pulkas_246.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_247','Ordino ietininkas',11,12,'- atakuodamas negauna tgalinės žalos.','/cards/sviesos-pulkas/Sviesos_Pulkas_247.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_248','Garbės šalmas',11,12,'- Pasirinktas su kiekvieno savo ėjimo pradžioje įgyja +1','/cards/sviesos-pulkas/Sviesos_Pulkas_248.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_249','Riterių mobilizacija',11,12,'Traukite 3 kortas, jei tai iškvieskite juos į kovos lauką. Jei kiti įmaišykite atgal į kaladę.','/cards/sviesos-pulkas/Sviesos_Pulkas_249.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_250','Liselotė',11,12,'- suteikia draugiškam','/cards/sviesos-pulkas/Sviesos_Pulkas_250.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_251','Gisela',11,12,'- jei kovos lauke turite su , suteikite jam','/cards/sviesos-pulkas/Sviesos_Pulkas_251.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_252','Klausas',11,12,'- visi draugiški įgyja +1','/cards/sviesos-pulkas/Sviesos_Pulkas_252.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_253','Margareta',11,12,'- atakuodama padaro','/cards/sviesos-pulkas/Sviesos_Pulkas_253.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_254-1','Brunhilda',11,12,'- pasirinktam draugiškam suteikia','/cards/sviesos-pulkas/Sviesos_Pulkas_254-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_254','Helga',11,12,'- pasirinktam draugiškam suteikia','/cards/sviesos-pulkas/Sviesos_Pulkas_254.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_255-1','Pulko sargyba',11,12,'Traukite 2 kortas. Jei tai iškvieskite juos į kovos lauką, jei kito tipo korta , įmaišykite atgal į kaladę.','/cards/sviesos-pulkas/Sviesos_Pulkas_255-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_255','Gunteris',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_255.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_256-1','Riteris gynėjas',11,12,'- suteikia pasirinktam .','/cards/sviesos-pulkas/Sviesos_Pulkas_256-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_256','Skydo mergelė',11,12,'- suteikia pasirinktam ir','/cards/sviesos-pulkas/Sviesos_Pulkas_256.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_257-1','Sunkusis riteris',11,12,'- “Sunkusis riteris” abu įgyja .','/cards/sviesos-pulkas/Sviesos_Pulkas_257-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_257','Ginklanešė Ulma',11,12,'- suteikia pasirinktam draugiškam','/cards/sviesos-pulkas/Sviesos_Pulkas_257.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_258','Ordino pėstininkas',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_258.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_259','Teisiantis žvilgsnis',11,12,'Traukite 3 kortas, pasirinkite dvi iš jų, trečią išmeskite į kapinyną.','/cards/sviesos-pulkas/Sviesos_Pulkas_259.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_260','Hildegardas',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_260.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_261','Ida',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_261.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_262','Alenė',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_262.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_263','Įkvepianti kalba',11,12,'Suteikia visiems draugiškiems kovos lauke +2','/cards/sviesos-pulkas/Sviesos_Pulkas_263.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_264','Miestiečių minia',11,12,'Suteikia visiems draugiškiems kovos lauke','/cards/sviesos-pulkas/Sviesos_Pulkas_264.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_265','Aneliesė',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_265.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_266','Adelheida',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_266.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_267','Frieda',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_267.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_268','Irmugarda',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_268.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_269','Riteris',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_269.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_270','Gizela Amelietė',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_270.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_271','Otas Fenbaueris',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_271.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_272','Otas Fenbaueris',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_272.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_273-1','Ulvydas Kantrusis',11,12,'- Kai šis patiria žalą - traukite kortą. Galioja karta per ėjimą.','/cards/sviesos-pulkas/Sviesos_Pulkas_273-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_273','Meidija',11,12,'- suteikia savo','/cards/sviesos-pulkas/Sviesos_Pulkas_273.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_274-1','Jėgos eleksyras',11,12,'Suteikia pasirinktam','/cards/sviesos-pulkas/Sviesos_Pulkas_274-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_274','Aršusis Manufas',11,12,NULL,'/cards/sviesos-pulkas/Sviesos_Pulkas_274.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_275-1','Dezertyras Ulfas',11,12,'- jei priešininkas kovos lauke turi “Dezertyras Ulfas” grįžta atgal į ranką.','/cards/sviesos-pulkas/Sviesos_Pulkas_275-1.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_275','Strėlių lietus',11,12,'Padaro po -1 ir visiems , kartoja šį efektą tol, kol bent vienas','/cards/sviesos-pulkas/Sviesos_Pulkas_275.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_276','Dorianos golemas',11,12,'Ėjimo pradžioje padaro draugiškam ir suteikia +2 iki sekančio tavo ėjimo. 12 Padaro draugiškam iki -2 kitam draugiškam suteikia iki +2 . Pasirinktas su iki sekančio tavo ėjimo gindamasis turi +3 .','/cards/sviesos-pulkas/Sviesos_Pulkas_276.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_277','Dorianos golemas',11,12,'Ėjimo pradžioje padaro draugiškam ir suteikia +4 iki sekančio tavo ėjimo. 15 Padaro draugiškam iki -4 kitam draugiškam suteikia iki +4 . Pasirinktas su iki sekančio tavo ėjimo gindamasis turi +6 .','/cards/sviesos-pulkas/Sviesos_Pulkas_277.webp','active',false),
('sviesos-pulkas/Sviesos_Pulkas_278','Dorianos golemas',11,12,'Ėjimo pradžioje padaro draugiškam ir suteikia +6 iki sekančio tavo ėjimo. 19 Padaro draugiškam iki -6 kitam draugiškam suteikia iki +6 . Pasirinktas su iki sekančio tavo ėjimo gindamasis turi +9 .','/cards/sviesos-pulkas/Sviesos_Pulkas_278.webp','active',false);