-- ⚠️ GENERUOTAS FAILAS (scripts/gen-handoff-registries.mjs) — nekeisk ranka.
-- 70 gamybinių pasiekimų iš asffa/asset-maps/achievement-manifest.csv
insert into public.rvn_achievements (code, sort_order, category, name_lt, requirement_lt, badge_file, status) values
  ('ach_01', 1, 'start', 'Pirmasis žingsnis', 'Susikurkite paskyrą ir pirmą kartą įeikite į žaidimą', '01-pirmasis-zingsnis.webp', 'generated'),
  ('ach_02', 2, 'start', 'Vardas įrašytas', 'Pasirinkite žaidėjo vardą', '02-vardas-irasytas.webp', 'generated'),
  ('ach_03', 3, 'start', 'Veidas Arenoje', 'Pasirinkite ne numatytąjį avatarą', '03-veidas-arenoje.webp', 'generated'),
  ('ach_04', 4, 'start', 'Kovos priesaika', 'Užbaikite mokymus', '04-kovos-priesaika.webp', 'generated'),
  ('ach_05', 5, 'start', 'Pirmoji kaladė', 'Išsaugokite galiojančią 30–40 kortų kaladę', '05-pirmoji-kalade.webp', 'generated'),
  ('ach_06', 6, 'start', 'Pirmasis susirėmimas', 'Užbaikite pirmąsias rungtynes', '06-pirmasis-susiremimas.webp', 'generated'),
  ('ach_07', 7, 'start', 'Pirmoji pergalė', 'Laimėkite pirmąsias Casual arba Ranked rungtynes', '07-pirmoji-pergale.webp', 'generated'),
  ('ach_08', 8, 'start', 'Pilnas profilis', 'Pasirinkite avatarą prisegtus ženklus ir profilio privatumo nustatymus', '08-pilnas-profilis.webp', 'generated'),
  ('ach_09', 9, 'combat', 'Kraujo krikštas', 'Užbaikite 10 rungtynių', '09-kraujo-krikstas.webp', 'generated'),
  ('ach_10', 10, 'combat', 'Arenos nuolatinis', 'Užbaikite 50 rungtynių', '10-arenos-nuolatinis.webp', 'generated'),
  ('ach_11', 11, 'combat', 'Šimtas susirėmimų', 'Užbaikite 100 rungtynių', '11-simtas-susiremimu.webp', 'generated'),
  ('ach_12', 12, 'combat', 'Karo veteranas', 'Užbaikite 250 rungtynių', '12-karo-veteranas.webp', 'generated'),
  ('ach_13', 13, 'combat', 'Pergalių skonis', 'Laimėkite 10 PvP rungtynių', '13-pergaliu-skonis.webp', 'generated'),
  ('ach_14', 14, 'combat', 'Kovų nugalėtojas', 'Laimėkite 50 PvP rungtynių', '14-kovu-nugaletojas.webp', 'generated'),
  ('ach_15', 15, 'combat', 'Šimtąkart triumfavęs', 'Laimėkite 100 PvP rungtynių', '15-simtakart-triumfaves.webp', 'generated'),
  ('ach_16', 16, 'combat', 'Arenos siaubas', 'Laimėkite 250 PvP rungtynių', '16-arenos-siaubas.webp', 'generated'),
  ('ach_17', 17, 'combat', 'Pergalių serija', 'Laimėkite 3 rungtynes iš eilės', '17-pergaliu-serija.webp', 'generated'),
  ('ach_18', 18, 'combat', 'Nenugalimas', 'Laimėkite 5 parinktas PvP rungtynes iš eilės', '18-nenugalimas.webp', 'generated'),
  ('ach_19', 19, 'tactics', 'Pirma reakcija', 'Panaudokite pirmą Reaction kortą', '19-pirma-reakcija.webp', 'generated'),
  ('ach_20', 20, 'tactics', 'Grandinės pradžia', 'Suaktyvinkite 2 Reaction vienoje grandinėje', '20-grandines-pradzia.webp', 'generated'),
  ('ach_21', 21, 'tactics', 'Reakcijų meistras', 'Panaudokite 50 Reaction', '21-reakciju-meistras.webp', 'generated'),
  ('ach_22', 22, 'tactics', 'Kovos šauksmas', 'Suaktyvinkite pirmą Battlecry', '22-kovos-sauksmas.webp', 'generated'),
  ('ach_23', 23, 'tactics', 'Šauklių armija', 'Suaktyvinkite 100 Battlecry arba summon efektų', '23-saukliu-armija.webp', 'generated'),
  ('ach_24', 24, 'tactics', 'Aukos kaina', 'Pirmą kartą sumokėkite Tribute', '24-aukos-kaina.webp', 'generated'),
  ('ach_25', 25, 'tactics', 'Čempiono iškilimas', 'Pasiekite Champion III fazę', '25-cempiono-iskilimas.webp', 'generated'),
  ('ach_26', 26, 'tactics', 'Lauko valdovas', 'Pakeiskite priešininko lauką', '26-lauko-valdovas.webp', 'generated'),
  ('ach_27', 27, 'tactics', 'Vienu smūgiu', 'Vienu efektu sunaikinkite 3 padarus', '27-vienu-smugiu.webp', 'generated'),
  ('ach_28', 28, 'tactics', 'Trigubas taikinys', 'Viena korta arba efektu paveikite 3 taikinius', '28-trigubas-taikinys.webp', 'generated'),
  ('ach_29', 29, 'tactics', 'Ant mirties slenksčio', 'Laimėkite kai herojui likę 5 arba mažiau HP', '29-ant-mirties-slenkscio.webp', 'generated'),
  ('ach_30', 30, 'tactics', 'Be įbrėžimo', 'Laimėkite nepatyrę žalos herojui', '30-be-ibrezimo.webp', 'generated'),
  ('ach_31', 31, 'decks', 'Kaladžių kalvis', 'Sukurkite 5 galiojančias kalades', '31-kaladziu-kalvis.webp', 'generated'),
  ('ach_32', 32, 'decks', 'Frakcijų eksperimentuotojas', 'Sužaiskite su 3 skirtingomis frakcijomis', '32-frakciju-eksperimentuotojas.webp', 'generated'),
  ('ach_33', 33, 'decks', 'Trijų vėliavų nugalėtojas', 'Laimėkite su 3 skirtingomis frakcijomis', '33-triju-veliavu-nugaletojas.webp', 'generated'),
  ('ach_34', 34, 'decks', 'Visų kelių keleivis', 'Sužaiskite su visomis 8 frakcijomis', '34-visu-keliu-keleivis.webp', 'generated'),
  ('ach_35', 35, 'decks', 'Visų frakcijų strategas', 'Laimėkite su visomis 8 frakcijomis', '35-visu-frakciju-strategas.webp', 'generated'),
  ('ach_36', 36, 'decks', 'Ištikimas vėliavai', 'Laimėkite 10 rungtynių su ta pačia frakcija', '36-istikimas-veliavai.webp', 'generated'),
  ('ach_37', 37, 'decks', 'Frakcijos čempionas', 'Laimėkite 50 rungtynių su ta pačia frakcija', '37-frakcijos-cempionas.webp', 'generated'),
  ('ach_38', 38, 'decks', 'Čempiono kaladė', 'Laimėkite su III fazės Champion', '38-cempiono-kalade.webp', 'generated'),
  ('ach_39', 39, 'decks', 'Burtų meistras', 'Laimėkite su kalade turinčia bent 12 burtų', '39-burtu-meistras.webp', 'generated'),
  ('ach_40', 40, 'decks', 'Padarų vadas', 'Laimėkite su kalade turinčia bent 20 padarų', '40-padaru-vadas.webp', 'generated'),
  ('ach_41', 41, 'collection', 'Pirmasis radinys', 'Gaukite pirmą kortą nepriklausančią pradinei kolekcijai', '41-pirmasis-radinys.webp', 'generated'),
  ('ach_42', 42, 'collection', 'Auganti kolekcija', 'Surinkite 50 unikalių kortų', '42-auganti-kolekcija.webp', 'generated'),
  ('ach_43', 43, 'collection', 'Kortų archyvas', 'Surinkite 100 unikalių kortų', '43-kortu-archyvas.webp', 'generated'),
  ('ach_44', 44, 'collection', 'Didžioji saugykla', 'Surinkite 200 unikalių kortų', '44-didzioji-saugykla.webp', 'generated'),
  ('ach_45', 45, 'collection', 'Ravenoro kolekcionierius', 'Surinkite 300 unikalių kortų', '45-ravenoro-kolekcionierius.webp', 'generated'),
  ('ach_46', 46, 'collection', 'Retas laimikis', 'Gaukite pirmą Rare kortą', '46-retas-laimikis.webp', 'generated'),
  ('ach_47', 47, 'collection', 'Epiškas radinys', 'Gaukite pirmą Epic kortą', '47-episkas-radinys.webp', 'generated'),
  ('ach_48', 48, 'collection', 'Legenda rankose', 'Gaukite pirmą Legendary kortą', '48-legenda-rankose.webp', 'generated'),
  ('ach_49', 49, 'collection', 'Čempionas pabudo', 'Gaukite pirmą Champion kortą', '49-cempionas-pabudo.webp', 'generated'),
  ('ach_50', 50, 'collection', 'Aštuonių vėliavų rinkinys', 'Surinkite po 10 unikalių kortų iš kiekvienos iš 8 frakcijų', '50-astuoniu-veliavu-rinkinys.webp', 'generated'),
  ('ach_51', 51, 'ranked', 'Pirmasis rangas', 'Užbaikite pirmąsias Ranked rungtynes', '51-pirmasis-rangas.webp', 'generated'),
  ('ach_52', 52, 'ranked', 'Įrašas lentelėje', 'Laimėkite pirmąsias Ranked rungtynes', '52-irasas-lenteleje.webp', 'generated'),
  ('ach_53', 53, 'ranked', 'Kylantis varžovas', 'Laimėkite 10 Ranked rungtynių', '53-kylantis-varzovas.webp', 'generated'),
  ('ach_54', 54, 'ranked', 'Arenos grėsmė', 'Laimėkite 50 Ranked rungtynių', '54-arenos-gresme.webp', 'generated'),
  ('ach_55', 55, 'ranked', 'Šimtas ranginių pergalių', 'Laimėkite 100 Ranked rungtynių', '55-simtas-ranginiu-pergaliu.webp', 'generated'),
  ('ach_56', 56, 'ranked', 'Sidabro slenkstis', 'Pirmą kartą pasiekite Silver pakopą', '56-sidabro-slenkstis.webp', 'generated'),
  ('ach_57', 57, 'ranked', 'Aukso vartai', 'Pirmą kartą pasiekite Gold pakopą', '57-aukso-vartai.webp', 'generated'),
  ('ach_58', 58, 'ranked', 'Aukso viršūnė', 'Pasiekite aukščiausią Gold pakopą', '58-aukso-virsune.webp', 'generated'),
  ('ach_59', 59, 'ranked', 'Sezono veteranas', 'Per vieną sezoną sužaiskite 50 Ranked rungtynių', '59-sezono-veteranas.webp', 'generated'),
  ('ach_60', 60, 'ranked', 'Auksinė pabaiga', 'Užbaikite sezoną Gold pakopoje', '60-auksine-pabaiga.webp', 'generated'),
  ('ach_61', 61, 'daily', 'Dienos darbas', 'Užbaikite pirmą Daily Quest', '61-dienos-darbas.webp', 'generated'),
  ('ach_62', 62, 'daily', 'Darbas baigtas', 'Per vieną dieną užbaikite visus 3 Daily Quest', '62-darbas-baigtas.webp', 'generated'),
  ('ach_63', 63, 'daily', 'Patikimas samdinys', 'Užbaikite 25 Daily Quest', null, 'pending'),
  ('ach_64', 64, 'daily', 'Šimtas užduočių', 'Užbaikite 100 Daily Quest', null, 'pending'),
  ('ach_65', 65, 'daily', 'Savaitės ritmas', 'Prisijunkite 7 dienas iš eilės', null, 'pending'),
  ('ach_66', 66, 'daily', 'Mėnesio ištvermė', 'Prisijunkite 30 dienų iš eilės', null, 'pending'),
  ('ach_67', 67, 'community', 'Vieša strategija', 'Paskelbkite pirmą viešą kaladę', null, 'pending'),
  ('ach_68', 68, 'community', 'Pirmas balsas', 'Balsuokite už kito žaidėjo kaladę', null, 'pending'),
  ('ach_69', 69, 'community', 'Bendruomenės kibirkštis', 'Gaukite 10 balsų už paskelbtą kaladę', null, 'pending'),
  ('ach_70', 70, 'community', 'Meta pėdsakas', 'Pasiekite kad jūsų kaladė būtų nukopijuota 25 kartus', null, 'pending')
on conflict (code) do update set
  sort_order = excluded.sort_order, category = excluded.category, name_lt = excluded.name_lt,
  requirement_lt = excluded.requirement_lt, badge_file = excluded.badge_file, status = excluded.status,
  updated_at = now();
